name: CI

# Controls when the action will run.
on:
  push:
    branches: dev

# Workflow to build and release windows and macos versions of the client.
jobs:
  # build and release job:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Build
        run: |
          yarn install
          yarn clean
          yarn build:lib
        if: always() # Pick up events even if the job fails or is canceled.